project:
  type: website
  output-dir: docs

website:
  title: "PSTAT5A"
  navbar:
    logo: /img/logo.png
    left:
      - icon: home
        href: index.qmd
        text: Home
      - schedule.qmd
      - syllabus.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



