project:
  type: website
  output-dir: docs

website:
  title: "PSTAT5A"
  site-url: "https://pstat5a.com"
  navbar:
    logo: "img/logo.png"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: calendar
        href: schedule.qmd
        text: "Class Schedule"
      - icon: file-earmark-text
        href: syllabus.qmd
        text: "Syllabus"
      - icon: book
        href: resources.qmd
        text: "Resources"
      - icon: envelope
        href: contact.qmd
        text: "Contact"

format:
  html:
    favicon: "img/logo.png"
    resources:
      - "img/logo.png"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true