project:
  type: website
  output-dir: docs

website:
  title: "PSTAT5A"
  favicon: /img/logo.png
  navbar:
    logo: /img/logo.png
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: "Class Schedule"
        icon: calendar
        href: schedule.qmd
      - text: "Syllabus"
        icon: file-earmark-text
        href: syllabus.qmd
      - text: "Resources"
        icon: book
        href: resources.qmd
      - text: "Contact"
        icon: envelope
        href: contact.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



