name: Render & Deploy Quarto site

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages     

    steps:
      - uses: actions/checkout@v3

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - uses: actions/configure-pages@v3

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs           
      - uses: actions/deploy-pages@v4